apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  labels:
    app: go-app
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80          # Port the service will expose
      targetPort: 8080   # The port on the container where the app listens
  type: ClusterIP        # Service type, can be LoadBalancer if exposed externally
